apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    released-by: gopaddle
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "gopaddle"
    meta.helm.sh/release-namespace: "gopaddle"
  name: gopaddle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gopaddle
  template:
    metadata:
      labels:
        released-by: gopaddle
        app: gopaddle
    spec:
      containers:
        - name: gopaddle-container
          image: gopaddle/gopaddle:{{ .Values.imageTag }}
          ports:
            - containerPort: 65080
          env:
            - name: CLUSTER_TYPE
              value: "{{ .Values.CLUSTER_TYPE }}"

