{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "gopaddle") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gopaddle
  labels:
    app.kubernetes.io/managed-by: "Helm"
    released-by: gopaddle
  annotations:
    meta.helm.sh/release-name: "gopaddle"
    meta.helm.sh/release-namespace: "gopaddle"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
{{- end }}
---
{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRoleBinding" "" "gopaddle") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gopaddle
  labels:
    app.kubernetes.io/managed-by: "Helm"
    released-by: gopaddle
  annotations:
    meta.helm.sh/release-name: "gopaddle"
    meta.helm.sh/release-namespace: "gopaddle"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gopaddle
subjects:
- kind: ServiceAccount
  name: default
  namespace: gopaddle
{{- end }}