apiVersion: v1
kind: Service
metadata:
  labels:
    released-by: gopaddle
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "gopaddle"
    meta.helm.sh/release-namespace: "gopaddle"
  name: gopaddle-service
spec:
  type: NodePort
  ports:
    - port: 65080
      targetPort: 65080
      nodePort: 30003
  selector:
    app: gopaddle

